services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - 9850:8080
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: unless-stopped
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/mysql
  importer:
    image: fireflyiii/data-importer:develop
    hostname: importer
    restart: unless-stopped
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
    volumes:
     - ./import:/import
    ports:
      - '9851:8080'
    depends_on:
      - app
    env_file: .importer.env
  # Reverse proxy using Caddy
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: firefly_iii_proxy
    ports:
      - "9852:80"
      - "9853:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - firefly_iii
    depends_on:
      - importer
      - app
  cron:
    image: alpine
    restart: unless-stopped
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata && \
      (ln -s /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    networks:
      - firefly_iii
    depends_on:
      - app

volumes:
   firefly_iii_upload:
   firefly_iii_db:
   caddy_data:
   caddy_config:

networks:
  firefly_iii:
    driver: bridge
